# Shell variables
# Generated by 'wal'
wallpaper="/home/shikikan/wallpaper/shizuku.png"

# Special
background='#1f2129'
foreground='#e9e7e7'
cursor='#e9e7e7'

# Colors
color0='#1f2129'
color1='#9EB5C8'
color2='#A8C7D8'
color3='#BBDFEF'
color4='#BAE1F3'
color5='#DAC0C1'
color6='#D1CCD6'
color7='#e9e7e7'
color8='#a3a1a1'
color9='#9EB5C8'
color10='#A8C7D8'
color11='#BBDFEF'
color12='#BAE1F3'
color13='#DAC0C1'
color14='#D1CCD6'
color15='#e9e7e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
